[versions]
ktlintGradle = "12.1.0"
spotless = "6.25.0"

[libraries]


[plugins]
ktlint-gradle = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
